//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TradeAssist.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TRADEASSIST_DIALOG          102
#define IDS_INVALID_TIMER               102
#define IDS_STRING_SERVER_INFO_INVALID  103
#define IDR_MAINFRAME                   128
#define IDR_WAVE_CLOSE_DEPOT            129
#define IDR_WAVE_DO_HIGH_CLOSE          129
#define IDR_WAVE_DO_LOW_CLOSE           131
#define IDC_EDIT_PRICE_DIFF             1000
#define IDC_EDIT_HIGH_PRICE_DIFF        1000
#define IDC_EDIT_COUNT                  1001
#define IDC_EDIT_LOW_DIRECTION_PRICE_DX 1002
#define IDC_EDIT_LOW_DIRECTION_PRICE_DY 1003
#define IDC_EDIT_LOW_PRICE_COUNT_DX     1004
#define IDC_EDIT_LOW_PRICE_COUNT_DY     1005
#define IDC_EDIT_HIGH_DIRECTION_PRICE_DX 1006
#define IDC_EDIT_HIGH_DIRECTION_PRICE_DY 1007
#define IDC_EDIT_HIGH_PRICE_COUNT_DX    1008
#define IDC_EDIT_HIGH_PRICE_COUNT_DY    1009
#define IDC_EDIT_COUNT_CONFIRM_DX       1010
#define IDC_EDIT_COUNT_CONFIRM_Dy       1011
#define IDC_EDIT_LOW_TAB_DIRECTION_DY   1012
#define IDC_EDIT_LOW_TAB_DIRECTION_DX   1013
#define IDC_EDIT_LEFT_TOP_TAB_DX        1014
#define IDC_EDIT_LEFT_TOP_TAB_DY        1015
#define IDC_EDIT_HIGH_TAB_DIRECTION_DX  1016
#define IDC_EDIT_HIGH_DIRECTION_PRICE_DY2 1017
#define IDC_EDIT_HIGH_TAB_DIRECTION_DY  1017
#define IDC_CHECK_AOTO_SUBMIT           1018
#define IDC_EDIT_LEFT_TOP_TAB_DX2       1019
#define IDC_CHECK_AOTO_SUBMIT2          1019
#define IDC_CHECK_FLASH_COMPLETE        1019
#define IDC_EDIT_START_DELETE_ORDER_DX  1019
#define IDC_CHECK_AOTO_CHASE            1019
#define IDC_EDIT1                       1020
#define IDC_EDIT_AUTO_COMPLETE_INTERVAL 1020
#define IDC_EDIT_START_DELETE_ORDER_DY  1021
#define IDC_EDIT_DELETE_CONFIRM_DX      1022
#define IDC_EDIT_DELETE_CONFIRM_DY      1023
#define IDC_EDIT_MSG_DELAY              1024
#define IDC_EDIT_HOUR                   1025
#define IDC_EDIT_MINUTE                 1026
#define IDC_EDIT_SECOND                 1027
#define IDC_BUTTON_START_TIMER          1028
#define IDC_CHECK_                      1029
#define IDC_CHECK_AUTO_CLOSE_DEPOT      1029
#define IDC_EDIT_LOW_PRICE_DIFF         1030
#define IDC_EDIT_DATAK_CURRENT_PRICE    1031
#define IDC_EDIT_DATAK_OPEN_PRICE       1032
#define IDC_EDIT_CURRENT_TIME           1033
#define IDC_EDIT_DATAK_OPEN_TIME        1034
#define IDC_EDIT_HIGH_PRICE             1035
#define IDC_EDIT_DATAK_LOW_PRICE        1036
#define IDC_EDIT_AUTO_CLOSE_THRESHOLD   1037
#define IDC_EDIT_DATAK_STATISTICS_UPDROP 1038
#define IDC_EDIT_DATAK_DAY_UPDROP       1039
#define IDC_CHECK_STATISTICS_DAY_UPDROP_AGREE 1040
#define IDC_EDIT_CURRENT_EXTREME_DIFF   1041
#define IDC_PROGRESS_AUTO_CLOSE_DEPOT   1042
#define IDC_RADI_HIGH                   1043
#define IDC_RADIO2                      1044
#define IDC_RADI_LOW                    1044
#define IDC_EDIT_SERVER_PORT            1047
#define IDC_EDIT_SERVER_HOST            1048
#define IDC_CHECK_OWN_SERVER            1049
#define IDC_CHECK_CONTINUOUS_PULL_PRICE 1049
#define IDC_EDIT_SERVER_PORT2           1049
#define IDC_EDIT_QURERY_PRICE_USE_TIME  1049
#define IDC_EDIT_DO_HTTP_REQUEST_INTERVAL 1050
#define IDC_CHECK_ENABLE_AUTO_THRESHOLD 1051
#define IDC_EDIT_NONFARMER_NUMBER       1052
#define IDC_EDIT_JOBLESS_RATE           1053
#define IDC_EDIT_CAPTURE_PRICE_USE_TIME 1054
#define IDC_CHECK_SET_MOST_TOP          1055
#define IDC_EDIT_NONFARMER_NUMBER_RESULT 1056
#define IDC_EDIT_JOBLESS_RATE_RESULT    1057
#define IDC_EDIT_NONFARMER_NUMBER_WEIGHT 1058
#define IDC_EDIT_JOBLESS_RATE3          1059
#define IDC_EDIT_JOBLESS_RATE_WEIGHT    1059
#define IDC_EDIT_NONFARMER_NUMBER_WEIGHT2 1060
#define IDC_EDIT_JOBLESS_RATE_WEIGHT2   1061
#define IDC_EDIT_TOTAL_CONCLUTION       1065

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
