//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TradeAssist.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TRADEASSIST_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDC_EDIT_PRICE_DIFF             1000
#define IDC_EDIT_COUNT                  1001
#define IDC_EDIT_LOW_DIRECTION_PRICE_DX 1002
#define IDC_EDIT_LOW_DIRECTION_PRICE_DY 1003
#define IDC_EDIT_LOW_PRICE_COUNT_DX     1004
#define IDC_EDIT_LOW_PRICE_COUNT_DY     1005
#define IDC_EDIT_HIGH_DIRECTION_PRICE_DX 1006
#define IDC_EDIT_HIGH_DIRECTION_PRICE_DY 1007
#define IDC_EDIT_HIGH_PRICE_COUNT_DX    1008
#define IDC_EDIT_HIGH_PRICE_COUNT_DY    1009
#define IDC_EDIT_COUNT_CONFIRM_DX       1010
#define IDC_EDIT_COUNT_CONFIRM_Dy       1011
#define IDC_EDIT_LOW_TAB_DIRECTION_DY   1012
#define IDC_EDIT_LOW_TAB_DIRECTION_DX   1013
#define IDC_EDIT_LEFT_TOP_TAB_DX        1014
#define IDC_EDIT_LEFT_TOP_TAB_DY        1015
#define IDC_EDIT_HIGH_TAB_DIRECTION_DX  1016
#define IDC_EDIT_HIGH_DIRECTION_PRICE_DY2 1017
#define IDC_EDIT_HIGH_TAB_DIRECTION_DY  1017
#define IDC_CHECK_AOTO_SUBMIT           1018
#define IDC_EDIT_LEFT_TOP_TAB_DX2       1019
#define IDC_CHECK_AOTO_SUBMIT2          1019
#define IDC_CHECK_FLASH_COMPLETE        1019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
